---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-shebang-scripts-are-executable
      - id: check-toml
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.5.4"
    hooks:
      - id: ruff
        args: [--exit-non-zero-on-fix, --fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        files: tracely/
        args: [--ignore-missing-imports]
        additional_dependencies:
          - types-requests
          - types-python-dateutil
